
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[263] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   22,   22,   41,   39,
       38,   38,   39,   39,   39,   39,   39,   40,   40,    2,
       40,   11,   14,   40,   40,   40,   15,   12,    8,   40,
       40,   13,   40,   40,    6,   40,   19,   18,   40,   35,
       34,   40,   21,   40,   28,   40,   29,   29,   40,   26,
       25,   24,   22,   22,   40,   38,    0,    0,    0,    0,
        0,    0,    0,   37,    2,    0,   11,   11,   14,    7,
        0,    0,    0,   15,   12,    8,    0,    0,   13,    0,

        0,   16,   13,    0,    0,    6,    0,   19,   18,    0,
       35,   34,    5,    0,   21,    0,   28,    0,    0,   30,
       29,   29,    0,   26,   25,   25,   24,   22,   22,    0,
        0,    0,   36,    0,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    0,   29,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   29,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   29,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       27,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   27,    0,   23,   23,    0,    0,    0,    0,    0,

        0,    7,    9,    0,    0,    0,   17,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   33,    0,    3,    0,   10,    0,    0,   20,    0,
        0,    1,    4,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   31,    0,    0,    0,    0,    0,    0,    0,    0,
       32,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    1,    1,    8,    9,    1,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,   11,    1,
        1,    1,    1,    1,   12,   13,   14,   15,   16,   17,
       17,   17,   18,   17,   19,   20,   21,   22,   23,   24,
       17,   25,   26,   27,   28,   29,   17,   17,   30,   17,
        1,    1,    1,    1,   31,    1,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[32] =
    {   0,
        1,    2,    2,    3,    4,    5,    6,    7,    1,    8,
        9,   10,   11,   11,   10,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       12
    } ;

static const flex_int16_t yy_base[301] =
    {   0,
        0,   17,  530,  529,   35,   66,   97,    0,  128,  159,
      189,  212,  236,  267,  298,  329,  360,  391,  422,  453,
      484,  515,  546,  577,  608,  639,  669,    0,  531, 1101,
        3,   20,  521,  509,  503,    0,  505,  511, 1101,    0,
        2,   45,  509,  508,    7,    9,  507,  506,    0,   20,
       43,   49,  486,  483,    0,   53, 1101,    0,   76, 1101,
        0,  503,    0,  697, 1101,   79,    0,  494,   51, 1101,
       58,    0,  725,   78,  493,   89,  501,  476,  486,  475,
      477,  473,  495, 1101,    0,   57,   92,  138,  493,  492,
      479,  149,  139,  478,  477,    0,   81,  469,  142,  145,

      143,  170,  173,  452,  460,    0,  176, 1101,    0,  196,
     1101,    0,  473,  472,    0,    0, 1101,  463,  199, 1101,
        0,  454,  148, 1101,  179,  182,    0,    0,  198,  461,
      452,  468, 1101,  454,  457,  454,  443,  450,  191,  204,
      219,  461,  431,  431,  422,  421,  423,  420,  421,  441,
      419,  185,  214,  205,  431,  414,  425,  424,  435,  422,
      419,  224,  409,  225,  227,  407,  409,  405,  394,  393,
      226,  414,  404,  404,  411,  220,  229,  394,  383,  386,
        0,  252,  399,  231,  394,  396,  244,  245,  404,  387,
      402, 1101,  262,  277,  258,  392,  392,  280,  383,  368,

      288,  292, 1101,  293,  369,  375,  283,  371,  359,  286,
      369,  368,  367,  362,  291,  358,  376,  349,  348,  373,
      360,  312,  371,  370,  369, 1101,  368,  355,  354,  285,
      315,  353, 1101,  308,  322,  341,  330,  339,  330,  348,
      326,  344,  343,  342,  337,  341,  340,  320,  316,  302,
      277, 1101,  229,  173,  166,   29,   13,  147,  317,  338,
     1101, 1101,  754,  766,  778,  790,  802,  814,  826,  838,
      850,  862,  874,  886,  898,  903,  914,  919,  927,  938,
      944,  946,  951,  956,  966,  971,  976,  986,  986,  997,
     1008, 1017, 1027, 1038, 1046, 1055, 1065, 1069, 1079, 1088

    } ;

static const flex_int16_t yy_def[301] =
    {   0,
      263,  263,  264,  264,  265,  265,  262,    7,  266,  266,
      267,  267,  268,  268,  269,  269,  270,  270,  271,  271,
      272,  272,  273,  273,  274,  274,  267,   27,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  275,  262,  276,
      277,  262,  262,  278,  278,  278,  262,  262,  279,  280,
      281,  262,  262,  262,  282,  262,  262,  283,  262,  262,
      284,  285,  286,  262,  262,  262,  287,  287,  288,  262,
      262,  289,  262,  262,  262,  262,  290,  262,  262,  262,
      262,  262,  275,  262,  276,  277,  262,  262,  262,  262,
      278,  278,  278,  262,  262,  279,  280,  262,  262,  262,

      281,  262,  262,  262,  262,  282,  262,  262,  283,  262,
      262,  284,  262,  285,  286,   64,  262,  262,  262,  262,
      287,  287,  288,  262,  262,  262,  289,   73,  262,  262,
      262,  290,  262,  262,  262,  262,  262,  262,  278,  278,
      262,  262,  262,  262,  287,  262,  262,  262,  262,  262,
      262,  278,  278,  262,  262,  262,  287,  262,  262,  262,
      262,  262,  262,  278,  278,  262,  262,  262,  287,  262,
      262,  262,  262,  262,  262,  278,  278,  262,  262,  262,
      287,  291,  262,  262,  262,  262,  262,  278,  278,  262,
      262,  262,  291,  291,  291,  262,  262,  262,  262,  262,

      278,  262,  262,  262,  262,  262,  262,  262,  262,  278,
      262,  262,  262,  262,  262,  262,  278,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  292,  262,  262,  262,
      293,  262,  262,  294,  293,  262,  262,  262,  262,  262,
      262,  295,  262,  296,  262,  297,  296,  262,  298,  262,
      298,  262,  262,  262,  262,  262,  299,  300,  262,  300,
      262,    0,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262

    } ;

static const flex_int16_t yy_nxt[1133] =
    {   0,
      262,   31,   32,   31,   76,   76,   76,   87,   33,   87,
       90,   34,   90,   35,   36,   80,  257,   37,   31,   32,
       31,   76,   76,   76,   81,   33,   98,   99,   34,   92,
       35,   36,  257,   93,   37,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   88,   88,   88,  101,
      103,  103,  103,  102,  107,  107,  107,  124,  125,  126,
      126,  126,   87,  108,   87,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,  110,  110,  110,
      119,  119,  119,  129,  129,  129,  111,   98,   99,  120,
       76,   76,   76,   88,   88,   88,   39,   39,   41,   41,

       41,   39,   42,   43,   42,   39,   39,   39,   44,   44,
       45,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       46,   44,   44,   44,   44,   44,   44,   39,   39,   39,
       39,   39,   39,   39,   47,   48,   39,   39,   39,   88,
       88,   88,   90,  103,  103,  103,  100,  100,  100,  101,
      259,   98,   90,  102,  124,  125,  140,  261,   39,   39,
       39,   39,   39,   39,   39,   47,   48,   39,   39,   39,
      139,  141,  141,  141,  103,  103,  103,  107,  107,  107,
      126,  126,  126,  126,  126,  126,  108,  256,   90,   39,
       50,   50,   50,  255,   90,   51,   52,  110,  110,  110,

      119,  119,  119,  129,  129,  129,  111,   90,  154,  120,
       53,  164,   54,   50,   50,   50,  152,   90,   51,   52,
      141,  141,  141,   90,  153,  165,  166,  162,   90,  171,
       90,  188,   90,   53,  184,   54,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,  187,   90,  176,
      174,  177,  183,  193,  193,  194,  254,  197,  189,  262,
      262,  200,  201,  193,  193,  194,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,  193,  193,
      194,  207,  207,  207,  207,  207,  207,  252,  230,   90,
      233,   90,  222,  222,  222,  202,  204,   39,   39,   56,

       56,   56,   39,   39,   39,   39,   39,   39,   57,  210,
      211,  212,  217,  222,  222,  222,  234,  234,  234,  236,
      259,  253,  237,  234,  234,  234,  252,  261,   39,   39,
       56,   56,   56,   39,   39,   39,   39,   39,   39,   57,
      245,  259,  250,  246,  246,  246,  245,  242,  261,  243,
      248,  242,  241,  240,  239,  238,  232,  229,  232,   39,
       39,   59,   59,   59,   39,   39,   39,   39,   39,   39,
       60,  227,  230,  224,  229,  228,  227,  226,  225,  224,
      223,  221,  220,  219,  218,  216,  215,  214,  213,  209,
       39,   39,   59,   59,   59,   39,   39,   39,   39,   39,

       39,   60,  208,  206,  205,  204,  203,  202,  199,  198,
      196,  192,  191,  190,  187,  186,  185,  184,  182,  181,
      180,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,  179,  178,  175,  173,  172,  171,  170,
      169,  168,  167,  163,  162,  161,  160,  159,  158,  157,
      156,  155,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,  154,  151,  150,  149,  148,  147,
      133,  146,  131,  145,  144,  113,  113,  143,  142,  102,
       95,   94,   90,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   90,   89,   84,  138,  137,

      136,  135,  134,  133,  131,  122,  113,  105,  104,   95,
       94,   90,   89,   84,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   82,   79,   78,   77,
      262,   39,   39,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,   39,   39,   64,   64,   64,
       39,   65,   66,   65,   39,  262,   39,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,   68,  262,   39,   39,   64,   64,
       64,   39,   65,   66,   65,   39,  262,   39,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,   68,  262,   39,   39,   69,
       69,   69,   39,   39,   70,   71,   39,  262,   39,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,   39,   39,
       69,   69,   69,   39,   39,   70,   71,   39,  262,   39,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,   39,
       73,   73,   73,  262,   74,   74,   74,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,   75,  116,  116,

      116,  262,  117,  262,  117,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  118,  128,  128,  128,  262,
      129,  129,  129,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  130,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       85,  262,   85,   85,   85,   86,   86,  262,   86,  262,
       86,   91,  262,  262,  262,  262,   91,  262,   91,   91,
       91,   96,   96,  262,   96,  262,   96,   96,   96,   97,
       97,  262,  262,   97,   97,  100,  100,  262,  262,  100,
      262,  262,  100,  106,  262,  106,  106,  106,  109,  262,
      109,  109,  109,  112,  262,  112,  112,  112,  114,  262,
      262,  262,  262,  114,  262,  114,  114,  114,  115,  262,
      115,  115,  115,  121,  262,  121,  121,  123,  123,  262,
      262,  123,  123,  127,  262,  127,  127,  132,  132,  132,

      132,  132,  132,  132,  132,  132,  132,  132,  132,  195,
      195,  195,  195,  195,  195,  195,  262,  195,  195,  231,
      262,  262,  262,  262,  262,  262,  231,  231,  235,  235,
      262,  262,  262,  262,  235,  262,  235,  235,  235,  234,
      234,  262,  262,  262,  262,  262,  262,  234,  244,  262,
      262,  262,  262,  262,  262,  244,  244,  247,  262,  262,
      262,  262,  247,  262,  247,  247,  247,  249,  262,  262,
      262,  262,  262,  262,  249,  249,  251,  251,  251,  251,
      251,  258,  262,  262,  262,  262,  262,  262,  258,  258,
      260,  262,  262,  262,  262,  260,  260,  260,  260,  260,

       29,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262
    } ;

static const flex_int16_t yy_chk[1133] =
    {   0,
        0,    1,    1,    1,   31,   31,   31,   41,    1,   41,
       45,    1,   46,    1,    1,   36,  257,    1,    2,    2,
        2,   32,   32,   32,   36,    2,   50,   50,    2,   45,
        2,    2,  256,   46,    2,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,   42,   42,   42,   51,
       52,   52,   52,   51,   56,   56,   56,   69,   69,   71,
       71,   71,   86,   56,   86,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,   59,   59,   59,
       66,   66,   66,   74,   74,   74,   59,   97,   97,   66,
       76,   76,   76,   87,   87,   87,    6,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   88,
       88,   88,   93,   99,   99,   99,  100,  100,  100,  101,
      258,  100,   92,  101,  123,  123,   93,  258,    9,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       92,  102,  102,  102,  103,  103,  103,  107,  107,  107,
      125,  125,  125,  126,  126,  126,  107,  255,  152,   10,
       11,   11,   11,  254,  139,   11,   11,  110,  110,  110,

      119,  119,  119,  129,  129,  129,  110,  140,  154,  119,
       11,  152,   11,   12,   12,   12,  139,  153,   12,   12,
      141,  141,  141,  176,  140,  153,  154,  162,  164,  171,
      165,  176,  177,   12,  184,   12,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,  187,  188,  164,
      162,  165,  171,  182,  182,  182,  253,  184,  177,  195,
      195,  187,  188,  193,  193,  193,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,  194,  194,
      194,  198,  198,  198,  207,  207,  207,  251,  230,  210,
      230,  201,  215,  215,  215,  202,  204,   14,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,  201,
      202,  204,  210,  222,  222,  222,  231,  231,  231,  234,
      259,  250,  234,  235,  235,  235,  249,  259,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
      245,  260,  248,  247,  246,  244,  243,  242,  260,  241,
      245,  240,  239,  238,  237,  236,  232,  229,  228,   16,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,  227,  225,  224,  223,  221,  220,  219,  218,  217,
      216,  214,  213,  212,  211,  209,  208,  206,  205,  200,
       17,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,   18,  199,  197,  196,  191,  190,  189,  186,  185,
      183,  180,  179,  178,  175,  174,  173,  172,  170,  169,
      168,   18,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,  167,  166,  163,  161,  160,  159,  158,
      157,  156,  155,  151,  150,  149,  148,  147,  146,  145,
      144,  143,   19,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,  142,  138,  137,  136,  135,  134,
      132,  131,  130,  122,  118,  114,  113,  105,  104,   98,
       95,   94,   91,   20,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   90,   89,   83,   82,   81,

       80,   79,   78,   77,   75,   68,   62,   54,   53,   48,
       47,   44,   43,   38,   21,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   37,   35,   34,   33,
       29,    4,    3,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   22,   23,   23,   23,   23,
       23,   23,   23,   23,   23,    0,   23,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   23,    0,   23,   24,   24,   24,
       24,   24,   24,   24,   24,   24,    0,   24,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   24,    0,   24,   25,   25,
       25,   25,   25,   25,   25,   25,   25,    0,   25,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   25,   26,
       26,   26,   26,   26,   26,   26,   26,   26,    0,   26,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   26,
       27,   27,   27,    0,   27,   27,   27,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   27,   64,   64,

       64,    0,   64,    0,   64,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   64,   73,   73,   73,    0,
       73,   73,   73,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   73,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      276,    0,  276,  276,  276,  277,  277,    0,  277,    0,
      277,  278,    0,    0,    0,    0,  278,    0,  278,  278,
      278,  279,  279,    0,  279,    0,  279,  279,  279,  280,
      280,    0,    0,  280,  280,  281,  281,    0,    0,  281,
        0,    0,  281,  282,    0,  282,  282,  282,  283,    0,
      283,  283,  283,  284,    0,  284,  284,  284,  285,    0,
        0,    0,    0,  285,    0,  285,  285,  285,  286,    0,
      286,  286,  286,  287,    0,  287,  287,  288,  288,    0,
        0,  288,  288,  289,    0,  289,  289,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  291,
      291,  291,  291,  291,  291,  291,    0,  291,  291,  292,
        0,    0,    0,    0,    0,    0,  292,  292,  293,  293,
        0,    0,    0,    0,  293,    0,  293,  293,  293,  294,
      294,    0,    0,    0,    0,    0,    0,  294,  295,    0,
        0,    0,    0,    0,    0,  295,  295,  296,    0,    0,
        0,    0,  296,    0,  296,  296,  296,  297,    0,    0,
        0,    0,    0,    0,  297,  297,  298,  298,  298,  298,
      298,  299,    0,    0,    0,    0,    0,    0,  299,  299,
      300,    0,    0,    0,    0,  300,  300,  300,  300,  300,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sql_parser.l"
#line 2 "sql_parser.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <regex.h>

struct Column {
  char *name;
  char *data_type;
  char *constraint;
  struct Column *next;
};

struct Table {
  char *name;
  char *primary_key;
  char *constraint_name;
  int num_columns;
  int num_records;
  struct Column *columns;
};

struct TableNode {
  struct Table table;
  struct TableNode *next;
};

struct TableNode *tables = NULL;
char *current_table;
bool primary_key_found;
int insert_columns, insert_values, insert_mode_columns;
#line 819 "lex.yy.c"

#line 821 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define TABLE_NAME 2
#define COLUMN_NAME 3
#define DATA_TYPE 4
#define CONSTRAINT_NAME 5
#define TABLE_PRIMARY_KEY 6
#define DESCRIBE_TABLE_NAME 7
#define DROP_TABLE_NAME 8
#define PRIMARY_CONSTRAINT_NAME 9
#define INSERT_TABLE_NAME 10
#define INSERT_VALUES 11
#define INSERT_COLUMNS 12
#define INSERT 13

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 51 "sql_parser.l"


#line 54 "sql_parser.l"
  /* ------------------------- */
  /*  CREATE TABLE STATE MACHINE */
  /* ------------------------- */

#line 1059 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 263 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1101 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 58 "sql_parser.l"
{ BEGIN(TABLE_NAME); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "sql_parser.l"
{
  // check if the table already exists
  struct TableNode *current = tables;
  while (current != NULL) {
    if (strcmp(current->table.name, yytext) == 0) {
      printf("Invalid command\n");
      BEGIN(INITIAL);
    }
    current = current->next;
  }

  // Create a new table
  struct TableNode *new_table = malloc(sizeof(struct TableNode));
  new_table->table.name = malloc(strlen(yytext) + 1);
  strcpy(new_table->table.name, yytext);
  new_table->table.primary_key = NULL;
  new_table->table.num_columns = 0;
  new_table->table.num_records = 0;
  new_table->table.columns = NULL;
  new_table->next = NULL;

  // Add the new table to the list of tables
  if (tables == NULL) {
    tables = new_table;
  } else {
    struct TableNode *current = tables;
    while (current->next != NULL) {
      current = current->next;
    }
    current->next = new_table;
  }

  current_table = malloc(strlen(yytext) + 1);
  strcpy(current_table, yytext);

  BEGIN(COLUMN_NAME);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "sql_parser.l"
{
  BEGIN(PRIMARY_CONSTRAINT_NAME);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 102 "sql_parser.l"
{ BEGIN(TABLE_PRIMARY_KEY); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 104 "sql_parser.l"
{
  // Add the constraint name to the current table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  current->table.constraint_name = malloc(strlen(yytext) + 1);

  yytext[strlen(yytext) - 1] = '\0'; // remove the trailing space
  strcpy(current->table.constraint_name, yytext);

  BEGIN(COLUMN_NAME);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 "sql_parser.l"
{
  // Add the primary key to the current table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  current->table.primary_key = malloc(strlen(yytext) + 1);
  strcpy(current->table.primary_key, yytext);

  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 130 "sql_parser.l"
{ 
  // check if the column already exists
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  struct Column *current_column = current->table.columns;
  while (current_column != NULL) {
    if (strcmp(current_column->name, yytext) == 0) {
      printf("Invalid command\n");
      BEGIN(INITIAL);
    }
    current_column = current_column->next;
  }

  // allocate memory for the new column
  struct Column *new_column = malloc(sizeof(struct Column));
  new_column->name = malloc(strlen(yytext) + 1);
  strcpy(new_column->name, yytext);
  new_column->data_type = NULL;
  new_column->constraint = NULL;

  // Add the new column to the list of columns
  if (current->table.columns == NULL) {
    current->table.columns = new_column;
  } else {
    struct Column *current_column = current->table.columns;
    while (current_column->next != NULL) {
      current_column = current_column->next;
    }
    current_column->next = new_column;
  }
  current->table.num_columns++;

  BEGIN(DATA_TYPE); 
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 167 "sql_parser.l"
{
  // Add the data type to the current column
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  struct Column *current_column = current->table.columns;
  while (current_column->next != NULL) {
    current_column = current_column->next;
  }

  current_column->data_type = malloc(strlen(yytext) + 1);
  strcpy(current_column->data_type, yytext);

  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 184 "sql_parser.l"
{
  // Add the constraint to the current column
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  struct Column *current_column = current->table.columns;
  while (current_column->next != NULL) {
    current_column = current_column->next;
  }

  // concat the constraint to the existing constraint
  if (current_column->constraint == NULL) {
    current_column->constraint = malloc(strlen(yytext) + 1);
    strcpy(current_column->constraint, yytext);
  } else {
    char *new_constraint = malloc(strlen(current_column->constraint) + strlen(yytext) + 2);
    strcpy(new_constraint, current_column->constraint);
    strcat(new_constraint, " ");
    strcat(new_constraint, yytext);
    free(current_column->constraint);
    current_column->constraint = new_constraint;
  }

  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 211 "sql_parser.l"
{
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }

  struct Column *current_column = current->table.columns;
  while (current_column->next != NULL) {
    current_column = current_column->next;
  }

  // set the table's primary key
  current->table.primary_key = malloc(strlen(current_column->name) + 1);
  strcpy(current->table.primary_key, current_column->name);
  
  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 229 "sql_parser.l"
{ BEGIN(COLUMN_NAME); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 230 "sql_parser.l"
{ BEGIN(COLUMN_NAME); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 231 "sql_parser.l"
{ BEGIN(COLUMN_NAME); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 233 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 234 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 235 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
/* ------------------------- */
/*  DESCRIBE TABLE STATE MACHINE */
/* ------------------------- */
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 243 "sql_parser.l"
{
  BEGIN(DESCRIBE_TABLE_NAME);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 246 "sql_parser.l"
{
  if (tables == NULL){
    printf("Invalid command\n");

  } else {
    struct TableNode *current = tables;
    while (current != NULL) {
      if (strcmp(current->table.name, yytext) == 0) {
        // print the table name
        printf("Table name: %s\n", yytext);

        // print the primary key
        if(current->table.constraint_name == NULL){
          printf("Primary key: %s\n", current->table.primary_key);
        } else {
          printf("Primary key: %s(%s)\n", current->table.constraint_name, current->table.primary_key);
        }
        break;
      }
      current = current->next;
    }

    // print the number of columns
    int num_columns = 0;
    struct Column *current_column = current->table.columns;
    while (current_column != NULL) {
      num_columns++;
      current_column = current_column->next;
    }
    printf("Number of columns: %d\n", num_columns);

    // print the number of records
    printf("Number of records: %d\n", current->table.num_records);
  }
  BEGIN(DESCRIBE_TABLE_NAME);
}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 283 "sql_parser.l"
{
  BEGIN(INITIAL);
}
	YY_BREAK
/* ------------------------- */
/*  INSERT TABLE STATE MACHINE */
/* ------------------------- */
case 20:
YY_RULE_SETUP
#line 293 "sql_parser.l"
{
  insert_mode_columns = 0;
  BEGIN(INSERT_TABLE_NAME);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 298 "sql_parser.l"
{
  if (tables == NULL){
    printf("Invalid command\n");
  } else {
    struct TableNode *current = tables;
    while (current != NULL) {
      if (strcmp(current->table.name, yytext) == 0) {
        strcpy(current_table, yytext);
        break;
      }
      current = current->next;
    }
  }
  BEGIN(INSERT);
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 314 "sql_parser.l"
{
  insert_columns = 0;
  insert_mode_columns = 1;
  BEGIN(INSERT_COLUMNS);
}
	YY_BREAK
/* read values */
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 321 "sql_parser.l"
{
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 325 "sql_parser.l"
{
  // increment the number of columns
  insert_columns++;

  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }

  if (insert_columns > current->table.num_columns) {
    printf("Invalid command\n");
    BEGIN(INITIAL);
  } else {
    BEGIN(INSERT_COLUMNS);
  }
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 342 "sql_parser.l"
{
  BEGIN(INSERT_COLUMNS);
}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 346 "sql_parser.l"
{
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 350 "sql_parser.l"
{
  insert_values = 0;
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 355 "sql_parser.l"
{
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 359 "sql_parser.l"
{
  printf("Value: %s\n", yytext);

  // increment the number of values
  insert_values++;

  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 368 "sql_parser.l"
{
  if (insert_mode_columns == 1 && insert_columns != insert_values) {
    printf("Invalid command\n");
  } 
  else {
    // increment the number of records
    struct TableNode *current = tables;
    while (strcmp(current->table.name, current_table) != 0) {
      current = current->next;
    }
    current->table.num_records++;
  }
  
  BEGIN(INITIAL);
}
	YY_BREAK
/* ------------------------- */
/*  ALTER TABLE STATE MACHINE */
/* ------------------------- */
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 389 "sql_parser.l"
{
	printf("%s\n", yytext);
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 392 "sql_parser.l"
{
	printf("%s\n", yytext);
}
	YY_BREAK
/* ------------------------- */
/*  DROP TABLE STATE MACHINE */
/* ------------------------- */
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 401 "sql_parser.l"
{
  BEGIN(DROP_TABLE_NAME);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 405 "sql_parser.l"
{
  if (tables == NULL) {
    printf("Invalid command\n");

  } else {
    int tableFound = 0;
    struct TableNode *current = tables;
    struct Table temp;

    // if only one table exists or if table is the last one
    if (current->next == NULL && strcmp(current->table.name, yytext) == 0) {
      printf("one table exists\n");
      tableFound = 1;
      temp = current->table;
      tables = NULL;
    }

    // if table is the first one
    if (tableFound == 0 && strcmp(current->table.name, yytext) == 0) {
      printf("table is the first one\n");
      tableFound = 1;
      temp = current->table;
      tables = current->next;
    }

    // if more than one table exists
    while (tableFound == 0 && current->next != NULL) {
      printf("current->next->table.name: %s\n", current->next->table.name);
      if (strcmp(current->next->table.name, yytext) == 0) {
        tableFound = 1;
        temp = current->next->table;
        current->next = current->next->next;
        break;
      }
      current = current->next;
    }

    // free the table
    if (tableFound) {
      free(temp.name);

      if (temp.constraint_name != NULL) {
        free(temp.constraint_name);
      }
      if (temp.primary_key != NULL) {
        free(temp.primary_key);
      }

      struct Column *current_column = temp.columns;
      while (current_column != NULL) {
        struct Column *tempCol = current_column;
        current_column = current_column->next;
        free(tempCol->name);
        free(tempCol->data_type);
        free(tempCol->constraint);
        free(tempCol);
      }
      printf("Table %s dropped\n", yytext);

      // print all tables names
      printf("Tables: ");
      current = tables;
      while (current != NULL) {
        printf("%s ", current->table.name);
        current = current->next;
      }
      printf(".\n");
    } else {
      printf("Invalid command\n");
    }
  }

  BEGIN(DROP_TABLE_NAME);
}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 480 "sql_parser.l"
{
  BEGIN(INITIAL);
}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 484 "sql_parser.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 485 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 487 "sql_parser.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 488 "sql_parser.l"
{ printf("Invalid command\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 490 "sql_parser.l"
ECHO;
	YY_BREAK
#line 1687 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(TABLE_NAME):
case YY_STATE_EOF(COLUMN_NAME):
case YY_STATE_EOF(DATA_TYPE):
case YY_STATE_EOF(CONSTRAINT_NAME):
case YY_STATE_EOF(TABLE_PRIMARY_KEY):
case YY_STATE_EOF(DESCRIBE_TABLE_NAME):
case YY_STATE_EOF(DROP_TABLE_NAME):
case YY_STATE_EOF(PRIMARY_CONSTRAINT_NAME):
case YY_STATE_EOF(INSERT_TABLE_NAME):
case YY_STATE_EOF(INSERT_VALUES):
case YY_STATE_EOF(INSERT_COLUMNS):
case YY_STATE_EOF(INSERT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 263 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 263 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 262);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 490 "sql_parser.l"


int main(void) {
  yylex();
  return 0;
}

void yyerror(const char *s) {
  printf("Error: %s\n", s);
}
