
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[263] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   47,   45,
       46,   45,   45,   45,   45,   45,   46,    2,   46,   11,
       14,   46,   46,   46,   15,   12,    8,   46,   46,   13,
       46,   46,    6,   46,   19,   18,   46,   41,   40,   46,
       21,   46,   29,   28,   46,   29,   46,   26,   25,   24,
       46,   22,   46,   32,   38,   46,   46,   35,   37,   36,
       44,    0,    0,    0,    0,    0,    0,    0,   43,    2,

        0,   11,   11,   14,    7,    0,    0,    0,   15,   12,
        8,    0,    0,   13,    0,    0,   16,   13,    0,    0,
        6,    0,   19,   18,    0,   41,   40,    5,    0,   21,
        0,   28,    0,   29,   30,   29,    0,   26,   25,   25,
       24,    0,   22,    0,    0,   32,    0,    0,   35,   37,
       36,    0,   42,    0,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    0,   29,    0,   33,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   29,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   27,    0,   23,
        0,    0,    0,    0,    0,    0,    0,    7,    9,    0,
        0,    0,    0,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   34,    0,    0,
       39,    0,    3,    0,   10,   31,    0,   20,    0,    1,
        4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    1,    1,    8,    9,    1,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,   11,    1,
        1,    1,    1,    1,   12,   13,   14,   15,   16,   17,
       17,   17,   18,   17,   19,   20,   21,   22,   23,   24,
       17,   25,   26,   27,   28,   29,   17,   17,   30,   17,
        1,    1,    1,    1,   31,    1,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[32] =
    {   0,
        1,    2,    2,    3,    4,    5,    6,    7,    1,    8,
        9,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,   10,    8,
       11
    } ;

static const flex_int16_t yy_base[300] =
    {   0,
        0,   16,  476,  475,   34,   65,   96,    0,  127,  158,
      188,  211,  235,  266,  297,  328,  359,  390,  421,  452,
      483,  514,  545,  576,  607,  638,  668,  696,  725,  756,
        5,   11,  787,  818,  849,  880,  911,  942,  477,  473,
     1306,    1,    4,    2,   30,   10,  472,    0,    0,   45,
      470,  469,   54,   25,  468,  467,    0,   44,   46,   57,
      447,  444,    0,   76, 1306,    0,   79, 1306,    0,  464,
        0,  972,    0, 1306,  456,  454,   55, 1306,   82,    0,
      141, 1306,  453,    0, 1306,  449,  426,    0,    0,    0,
     1306,  447,  422,  432,  421,  423,  419,  441, 1306,    0,

       48,   89,  137,  439,  438,  437,  149,  138,  436,  435,
        0,   81,  427,  141,  147,  141,  170,  173,  410,  418,
        0,  176, 1306,    0,  182, 1306,    0,  431,  430,    0,
        0, 1306,  421,    0, 1306,  400,   87, 1306,  179,  195,
        0,  182, 1306,  407,  398,    0,  402,  393,    0,    0,
        0,  412, 1306,  398,  401,  398,  387,  394,  190,  196,
      199,  405,  387,  387,  378,  377, 1306,  380,  378,  375,
      364,  384,  362,  200,  216,  201,  374,  357,  368,  367,
      245,  378,  365,  362,  202,  352,  205,  227,  350,  352,
      360,  349,  348,  251,  350,  230,  368,  358,  346,  353,

      220,  221,  336,  325,  328,    0,  258,  333,  340,  252,
      335,  337,  203,  204,  345,  328,  343, 1306,  278, 1306,
      318,  332,  332,  283,  323,  320,  274,  290, 1306,  291,
      320,  320,  314,  286,  310,  298,  287,  308,  307,  300,
      305,  300,  309,  296,  314,  263,  262, 1306,  279,  247,
      313,  254,  246,  222, 1306,  142,   60,   17,  151,    7,
     1306, 1306, 1001, 1012, 1023, 1034, 1045, 1056, 1067, 1078,
     1089, 1100, 1111, 1122, 1133, 1144, 1155, 1166, 1177, 1181,
     1191, 1196, 1203, 1213, 1219, 1221, 1225, 1229, 1238, 1242,
     1250, 1259, 1259, 1268, 1271, 1275, 1279, 1283, 1294

    } ;

static const flex_int16_t yy_def[300] =
    {   0,
      263,  263,  264,  264,  265,  265,  262,    7,  266,  266,
      267,  267,  268,  268,  269,  269,  270,  270,  271,  271,
      272,  272,  273,  273,  274,  274,  267,  267,  275,  275,
      267,  267,  276,  276,  277,  277,  278,  278,  262,  262,
      262,  262,  262,  262,  262,  262,  279,  280,  281,  262,
      262,  282,  282,  282,  262,  262,  283,  284,  285,  262,
      262,  262,  286,  262,  262,  287,  262,  262,  288,  289,
      290,  262,  291,  262,  262,  291,  292,  262,  262,  293,
      294,  262,  262,  295,  262,  262,  262,  296,  297,  298,
      262,  299,  262,  262,  262,  262,  262,  279,  262,  280,

      281,  262,  262,  262,  262,  282,  282,  282,  262,  262,
      283,  284,  262,  262,  262,  285,  262,  262,  262,  262,
      286,  262,  262,  287,  262,  262,  288,  262,  289,  290,
       72,  262,  262,  291,  262,  291,  292,  262,  262,  262,
      293,  294,  262,  262,  262,  295,  262,  262,  296,  297,
      298,  299,  262,  262,  262,  262,  262,  262,  282,  282,
      262,  262,  262,  262,  291,  262,  262,  262,  262,  262,
      262,  262,  262,  282,  282,  262,  262,  262,  291,  262,
      262,  262,  262,  262,  262,  262,  282,  282,  262,  262,
      262,  291,  262,  262,  262,  262,  262,  262,  262,  262,

      282,  282,  262,  262,  262,  291,  262,  262,  262,  262,
      262,  262,  262,  282,  282,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  282,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  282,  262,  262,  262,
      262,  262,  262,  262,  282,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,    0,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262

    } ;

static const flex_int16_t yy_nxt[1338] =
    {   0,
      262,  262,   41,   91,   91,  102,   91,  102,   42,   92,
      260,   43,   91,   44,   45,   85,   86,   46,   41,   87,
      258,   85,   86,   93,   42,   87,   94,   43,  105,   44,
       45,   97,   91,   46,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   95,  103,  103,  103,  108,
      113,  114,  116,  102,   96,  102,  117,  105,  118,  118,
      118,  138,  139,  260,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  107,  122,  122,  122,
      125,  125,  125,  140,  140,  140,  123,  113,  114,  126,
      103,  103,  103,  138,  139,   41,   41,   49,   49,   49,

       41,   50,   51,   50,   41,   41,   41,   52,   52,   53,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   54,
       52,   52,   52,   52,   52,   52,   41,   41,   41,   41,
       41,   41,   41,   55,   56,   41,   41,   41,  103,  103,
      103,  105,  118,  118,  118,  256,  143,  116,  115,  115,
      115,  117,  105,  113,  259,  160,  261,   41,   41,   41,
       41,   41,   41,   41,   55,   56,   41,   41,   41,  144,
      159,  161,  161,  161,  118,  118,  118,  122,  122,  122,
      140,  140,  140,  125,  125,  125,  123,  143,   41,   58,
       58,   58,  126,  105,   59,   60,  140,  140,  140,  105,

      161,  161,  161,  105,  176,  185,  213,  105,  105,   61,
      144,   62,   58,   58,   58,  174,  175,   59,   60,  105,
      226,  227,  189,  105,  105,  259,  187,  188,  199,  201,
      105,  214,   61,  196,   62,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  194,  194,  194,  253,
      215,  202,  194,  194,  194,  210,  209,  258,  195,  219,
      219,  219,  257,  220,  195,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,  105,  223,  219,
      219,  219,  256,  220,  234,  234,  234,  234,  234,  234,
      105,  255,  254,  228,  230,  237,   41,   41,   64,   64,

       64,   41,   41,   41,   41,   41,   41,   65,  238,  239,
      251,  251,  251,  245,  251,  251,  251,  253,  252,  250,
      249,  248,  247,  246,  244,  243,  242,   41,   41,   64,
       64,   64,   41,   41,   41,   41,   41,   41,   65,  241,
      240,  236,  235,  233,  232,  231,  230,  229,  228,  225,
      224,  222,  221,  218,  217,  216,  213,  212,   41,   41,
       67,   67,   67,   41,   41,   41,   41,   41,   41,   68,
      211,  210,  208,  207,  206,  205,  204,  203,  200,  198,
      197,  196,  193,  192,  191,  190,  186,  185,  184,   41,
       41,   67,   67,   67,   41,   41,   41,   41,   41,   41,

       68,  183,  182,  181,  180,  179,  178,  177,  176,  173,
      172,  171,  170,  169,  153,  168,  167,  166,  145,  165,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,  164,  128,  128,  163,  162,  117,  110,  109,
      105,  105,  104,   99,  158,  157,  156,  155,  154,  153,
      148,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,  147,  145,  136,  135,  128,  120,  119,
      110,  109,  105,  104,   99,   91,  262,   41,   41,  262,
      262,  262,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,   41,   41,   72,   72,   72,  262,
       74,   75,   74,   41,  262,   41,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,   76,  262,   41,   41,   72,   72,   72,
      262,   74,   75,   74,   41,  262,   41,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,   76,  262,   41,   41,   77,   77,
       77,   41,   41,   78,   79,   41,  262,   41,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,   41,   41,   77,
       77,   77,   41,   41,   78,   79,   41,  262,   41,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,   41,   81,
       81,   81,  262,   82,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,   83,   81,   81,   81,

      262,   82,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,   83,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,   41,  131,  131,  131,  262,  132,  262,  132,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      133,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,  100,  262,
      100,  100,  101,  101,  262,  101,  262,  101,  106,  262,

      262,  262,  262,  106,  262,  106,  106,  111,  111,  262,
      111,  262,  111,  111,  112,  112,  262,  262,  112,  112,
      115,  115,  262,  262,  115,  262,  262,  115,  121,  262,
      121,  121,  124,  262,  124,  124,  127,  262,  127,  127,
      129,  262,  262,  262,  262,  129,  262,  129,  129,  130,
      262,  130,  130,  134,  262,  262,  262,  134,  262,  134,
      137,  137,  262,  262,  137,  137,  141,  262,  141,  142,
      142,  262,  142,  262,  262,  262,  262,  142,  146,  262,
      146,  146,  149,  262,  149,  149,  150,  262,  150,  150,
      151,  262,  151,  151,  152,  152,  152,  152,  152,  152,

      152,  152,  152,  152,  152,   39,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262
    } ;

static const flex_int16_t yy_chk[1338] =
    {   0,
        0,    0,    1,   42,   44,   49,   43,   49,    1,   42,
      260,    1,   46,    1,    1,   31,   31,    1,    2,   31,
      258,   32,   32,   43,    2,   32,   44,    2,   54,    2,
        2,   46,   45,    2,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,   45,   50,   50,   50,   54,
       58,   58,   59,  101,   45,  101,   59,   53,   60,   60,
       60,   77,   77,  257,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,   53,   64,   64,   64,
       67,   67,   67,   79,   79,   79,   64,  112,  112,   67,
      102,  102,  102,  137,  137,    6,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,  103,  103,
      103,  108,  114,  114,  114,  256,   81,  116,  115,  115,
      115,  116,  107,  115,  259,  108,  259,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   81,
      107,  117,  117,  117,  118,  118,  118,  122,  122,  122,
      139,  139,  139,  125,  125,  125,  122,  142,   10,   11,
       11,   11,  125,  159,   11,   11,  140,  140,  140,  160,

      161,  161,  161,  174,  176,  185,  213,  214,  187,   11,
      142,   11,   12,   12,   12,  159,  160,   12,   12,  175,
      213,  214,  176,  201,  202,  254,  174,  175,  185,  187,
      188,  201,   12,  196,   12,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,  181,  181,  181,  253,
      202,  188,  194,  194,  194,  210,  196,  252,  181,  207,
      207,  207,  250,  207,  194,   13,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,  227,  210,  219,
      219,  219,  249,  219,  224,  224,  224,  234,  234,  234,
      237,  247,  246,  228,  230,  227,   14,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,  228,  230,
      243,  243,  243,  237,  251,  251,  251,  245,  244,  242,
      241,  240,  239,  238,  236,  235,  233,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,  232,
      231,  226,  225,  223,  222,  221,  217,  216,  215,  212,
      211,  209,  208,  205,  204,  203,  200,  199,   16,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
      198,  197,  195,  193,  192,  191,  190,  189,  186,  184,
      183,  182,  180,  179,  178,  177,  173,  172,  171,   17,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,  170,  169,  168,  166,  165,  164,  163,  162,  158,
      157,  156,  155,  154,  152,  148,  147,  145,  144,  136,
       18,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,  133,  129,  128,  120,  119,  113,  110,  109,
      106,  105,  104,   98,   97,   96,   95,   94,   93,   92,
       87,   19,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   86,   83,   76,   75,   70,   62,   61,
       56,   55,   52,   51,   47,   40,   39,    4,    3,    0,
        0,    0,   20,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   21,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   22,   23,   23,   23,   23,    0,
       23,   23,   23,   23,    0,   23,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   23,    0,   23,   24,   24,   24,   24,
        0,   24,   24,   24,   24,    0,   24,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   24,    0,   24,   25,   25,   25,
       25,   25,   25,   25,   25,   25,    0,   25,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   25,   26,   26,
       26,   26,   26,   26,   26,   26,   26,    0,   26,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   26,   27,
       27,   27,    0,   27,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   27,   28,   28,   28,

        0,   28,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   28,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   29,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   30,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   33,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   34,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   35,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       36,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   37,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   38,   72,   72,   72,    0,   72,    0,   72,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       72,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  280,    0,
      280,  280,  281,  281,    0,  281,    0,  281,  282,    0,

        0,    0,    0,  282,    0,  282,  282,  283,  283,    0,
      283,    0,  283,  283,  284,  284,    0,    0,  284,  284,
      285,  285,    0,    0,  285,    0,    0,  285,  286,    0,
      286,  286,  287,    0,  287,  287,  288,    0,  288,  288,
      289,    0,    0,    0,    0,  289,    0,  289,  289,  290,
        0,  290,  290,  291,    0,    0,    0,  291,    0,  291,
      292,  292,    0,    0,  292,  292,  293,    0,  293,  294,
      294,    0,  294,    0,    0,    0,    0,  294,  295,    0,
      295,  295,  296,    0,  296,  296,  297,    0,  297,  297,
      298,    0,  298,  298,  299,  299,  299,  299,  299,  299,

      299,  299,  299,  299,  299,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sql_parser.l"
#line 2 "sql_parser.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <regex.h>

struct Column {
  char *name;
  char *data_type;
  char *constraint;
  struct Column *next;
};

struct Table {
  char *name;
  char *primary_key;
  char *constraint_name;
  int num_columns;
  int num_records;
  struct Column *columns;
};

struct TableNode {
  struct Table table;
  struct TableNode *next;
};

struct TableNode *tables = NULL;
char *current_table;
bool primary_key_found;
int insert_columns, insert_values, insert_mode_columns;
#line 863 "lex.yy.c"

#line 865 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define TABLE_NAME 2
#define COLUMN_NAME 3
#define DATA_TYPE 4
#define CONSTRAINT_NAME 5
#define TABLE_PRIMARY_KEY 6
#define DESCRIBE_TABLE_NAME 7
#define DROP_TABLE_NAME 8
#define PRIMARY_CONSTRAINT_NAME 9
#define INSERT_TABLE_NAME 10
#define INSERT_VALUES 11
#define INSERT_COLUMNS 12
#define INSERT 13
#define ALTER_TABLE_NAME 14
#define ALTER_TABLE 15
#define ALTER_TABLE_ADD 16
#define ALTER_TABLE_DROP 17
#define ALTER_TABLE_ADD_TYPE 18

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 56 "sql_parser.l"


#line 59 "sql_parser.l"
  /* ------------------------- */
  /*  CREATE TABLE STATE MACHINE */
  /* ------------------------- */

#line 1108 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 263 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1306 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "sql_parser.l"
{ BEGIN(TABLE_NAME); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "sql_parser.l"
{
  // check if the table already exists
  struct TableNode *current = tables;
  while (current != NULL) {
    if (strcmp(current->table.name, yytext) == 0) {
      printf("Invalid command\n");
      BEGIN(INITIAL);
    }
    current = current->next;
  }

  // Create a new table
  struct TableNode *new_table = malloc(sizeof(struct TableNode));
  new_table->table.name = malloc(strlen(yytext) + 1);
  strcpy(new_table->table.name, yytext);
  new_table->table.primary_key = NULL;
  new_table->table.num_columns = 0;
  new_table->table.num_records = 0;
  new_table->table.columns = NULL;
  new_table->next = NULL;

  // Add the new table to the list of tables
  if (tables == NULL) {
    tables = new_table;
  } else {
    struct TableNode *current = tables;
    while (current->next != NULL) {
      current = current->next;
    }
    current->next = new_table;
  }

  current_table = malloc(strlen(yytext) + 1);
  strcpy(current_table, yytext);

  BEGIN(COLUMN_NAME);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 103 "sql_parser.l"
{
  BEGIN(PRIMARY_CONSTRAINT_NAME);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "sql_parser.l"
{ BEGIN(TABLE_PRIMARY_KEY); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 109 "sql_parser.l"
{
  // Add the constraint name to the current table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  current->table.constraint_name = malloc(strlen(yytext) + 1);

  yytext[strlen(yytext) - 1] = '\0'; // remove the trailing space
  strcpy(current->table.constraint_name, yytext);

  BEGIN(COLUMN_NAME);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 "sql_parser.l"
{
  // Add the primary key to the current table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  current->table.primary_key = malloc(strlen(yytext) + 1);
  strcpy(current->table.primary_key, yytext);

  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 135 "sql_parser.l"
{ 
  // check if the column already exists
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  struct Column *current_column = current->table.columns;
  while (current_column != NULL) {
    if (strcmp(current_column->name, yytext) == 0) {
      printf("Invalid command\n");
      BEGIN(INITIAL);
    }
    current_column = current_column->next;
  }

  // allocate memory for the new column
  struct Column *new_column = malloc(sizeof(struct Column));
  new_column->name = malloc(strlen(yytext) + 1);
  strcpy(new_column->name, yytext);
  new_column->data_type = NULL;
  new_column->constraint = NULL;

  // Add the new column to the list of columns
  if (current->table.columns == NULL) {
    current->table.columns = new_column;
  } else {
    struct Column *current_column = current->table.columns;
    while (current_column->next != NULL) {
      current_column = current_column->next;
    }
    current_column->next = new_column;
  }
  current->table.num_columns++;

  BEGIN(DATA_TYPE); 
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 172 "sql_parser.l"
{
  // Add the data type to the current column
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  struct Column *current_column = current->table.columns;
  while (current_column->next != NULL) {
    current_column = current_column->next;
  }

  current_column->data_type = malloc(strlen(yytext) + 1);
  strcpy(current_column->data_type, yytext);

  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 189 "sql_parser.l"
{
  // Add the constraint to the current column
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  struct Column *current_column = current->table.columns;
  while (current_column->next != NULL) {
    current_column = current_column->next;
  }

  // concat the constraint to the existing constraint
  if (current_column->constraint == NULL) {
    current_column->constraint = malloc(strlen(yytext) + 1);
    strcpy(current_column->constraint, yytext);
  } else {
    char *new_constraint = malloc(strlen(current_column->constraint) + strlen(yytext) + 2);
    strcpy(new_constraint, current_column->constraint);
    strcat(new_constraint, " ");
    strcat(new_constraint, yytext);
    free(current_column->constraint);
    current_column->constraint = new_constraint;
  }

  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 216 "sql_parser.l"
{
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }

  struct Column *current_column = current->table.columns;
  while (current_column->next != NULL) {
    current_column = current_column->next;
  }

  // set the table's primary key
  current->table.primary_key = malloc(strlen(current_column->name) + 1);
  strcpy(current->table.primary_key, current_column->name);
  
  BEGIN(CONSTRAINT_NAME);
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 234 "sql_parser.l"
{ BEGIN(COLUMN_NAME); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 235 "sql_parser.l"
{ BEGIN(COLUMN_NAME); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 236 "sql_parser.l"
{ BEGIN(COLUMN_NAME); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 238 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 239 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 240 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
/* ------------------------- */
/*  DESCRIBE TABLE STATE MACHINE */
/* ------------------------- */
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 248 "sql_parser.l"
{
  BEGIN(DESCRIBE_TABLE_NAME);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 251 "sql_parser.l"
{
  if (tables == NULL){
    printf("Invalid command\n");

  } else {
    struct TableNode *current = tables;
    while (current != NULL) {
      if (strcmp(current->table.name, yytext) == 0) {
        // print the table name
        printf("Table name: %s\n", yytext);

        // print the primary key
        if(current->table.constraint_name == NULL){
          printf("Primary key: %s\n", current->table.primary_key);
        } else {
          printf("Primary key: %s(%s)\n", current->table.constraint_name, current->table.primary_key);
        }
        break;
      }
      current = current->next;
    }

    // print the number of columns
    int num_columns = 0;
    struct Column *current_column = current->table.columns;
    while (current_column != NULL) {
      num_columns++;
      current_column = current_column->next;
    }
    printf("Number of columns: %d\n", num_columns);

    // print the number of records
    printf("Number of records: %d\n", current->table.num_records);
  }
  BEGIN(DESCRIBE_TABLE_NAME);
}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 288 "sql_parser.l"
{
  BEGIN(INITIAL);
}
	YY_BREAK
/* ------------------------- */
/*  INSERT TABLE STATE MACHINE */
/* ------------------------- */
case 20:
YY_RULE_SETUP
#line 298 "sql_parser.l"
{
  insert_mode_columns = 0;
  BEGIN(INSERT_TABLE_NAME);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 303 "sql_parser.l"
{
  if (tables == NULL){
    printf("Invalid command\n");
  } else {
    struct TableNode *current = tables;
    while (current != NULL) {
      if (strcmp(current->table.name, yytext) == 0) {
        strcpy(current_table, yytext);
        break;
      }
      current = current->next;
    }
  }
  BEGIN(INSERT);
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 319 "sql_parser.l"
{
  insert_columns = 0;
  insert_mode_columns = 1;
  BEGIN(INSERT_COLUMNS);
}
	YY_BREAK
/* read values */
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 326 "sql_parser.l"
{
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 330 "sql_parser.l"
{
  // increment the number of columns
  insert_columns++;

  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }

  if (insert_columns > current->table.num_columns) {
    printf("Invalid command\n");
    BEGIN(INITIAL);
  } else {
    BEGIN(INSERT_COLUMNS);
  }
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 347 "sql_parser.l"
{
  BEGIN(INSERT_COLUMNS);
}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 351 "sql_parser.l"
{
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 355 "sql_parser.l"
{
  insert_values = 0;
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 360 "sql_parser.l"
{
  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 364 "sql_parser.l"
{
  // increment the number of values
  insert_values++;

  BEGIN(INSERT_VALUES);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 371 "sql_parser.l"
{
  if (insert_mode_columns == 1 && insert_columns != insert_values) {
    printf("Invalid command\n");
  } 
  else {
    // increment the number of records
    struct TableNode *current = tables;
    while (strcmp(current->table.name, current_table) != 0) {
      current = current->next;
    }
    current->table.num_records++;
  }
  
  BEGIN(INITIAL);
}
	YY_BREAK
/* ------------------------- */
/*  ALTER TABLE STATE MACHINE */
/* ------------------------- */
case 31:
YY_RULE_SETUP
#line 392 "sql_parser.l"
{
  BEGIN(ALTER_TABLE_NAME);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 396 "sql_parser.l"
{
  int found = 0;
  if (tables == NULL){
    printf("Invalid command\n");
  } else {
    struct TableNode *current = tables;
    while (current != NULL) {
      if (strcmp(current->table.name, yytext) == 0) {
        strcpy(current_table, yytext);
        found = 1;
        break;
      }
      current = current->next;
    }
  }
  if (found == 0) {
    printf("Invalid command\n");
    BEGIN(INITIAL);
  } else {
    BEGIN(ALTER_TABLE);
  }
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 419 "sql_parser.l"
{
  BEGIN(ALTER_TABLE_ADD);
}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 423 "sql_parser.l"
{
  BEGIN(ALTER_TABLE_DROP);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 427 "sql_parser.l"
{
  printf("Column: %s\n", yytext);

  // add the column to the table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  current->table.num_columns++;

  struct Column *newColumn = (struct Column *) malloc(sizeof(struct Column));
  newColumn->name = (char *) malloc(strlen(yytext) + 1);
  strcpy(newColumn->name, yytext);
  newColumn->next = NULL;

  if (current->table.columns == NULL) {
    current->table.columns = newColumn;
  } else {
    struct Column *currentColumn = current->table.columns;
    while (currentColumn->next != NULL) {
      currentColumn = currentColumn->next;
    }
    currentColumn->next = newColumn;
  }

  BEGIN(ALTER_TABLE_ADD_TYPE);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 455 "sql_parser.l"
{
  printf("Type: %s\n", yytext);

  // add the type to the table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }

  struct Column *currentColumn = current->table.columns;
  while (currentColumn->next != NULL) {
    currentColumn = currentColumn->next;
  }
  currentColumn->data_type = (char *) malloc(strlen(yytext) + 1);
  strcpy(currentColumn->data_type, yytext);

  BEGIN(ALTER_TABLE);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 474 "sql_parser.l"
{
  printf("Column: %s\n", yytext);

  // remove the column from the table
  struct TableNode *current = tables;
  while (strcmp(current->table.name, current_table) != 0) {
    current = current->next;
  }
  current->table.num_columns--;

  struct Column *currentColumn = current->table.columns;
  struct Column *previousColumn = NULL;
  while (currentColumn != NULL) {
    if (strcmp(currentColumn->name, yytext) == 0) {
      if (previousColumn == NULL) {
        current->table.columns = currentColumn->next;
      } else {
        previousColumn->next = currentColumn->next;
      }
      free(currentColumn);
      break;
    }
    previousColumn = currentColumn;
    currentColumn = currentColumn->next;
  }

  BEGIN(ALTER_TABLE);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 503 "sql_parser.l"
{
  BEGIN(INITIAL);
}
	YY_BREAK
/* ------------------------- */
/*  DROP TABLE STATE MACHINE */
/* ------------------------- */
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 511 "sql_parser.l"
{
  BEGIN(DROP_TABLE_NAME);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 515 "sql_parser.l"
{
  if (tables == NULL) {
    printf("Invalid command\n");

  } else {
    int tableFound = 0;
    struct TableNode *current = tables;
    struct Table temp;

    // if only one table exists or if table is the last one
    if (current->next == NULL && strcmp(current->table.name, yytext) == 0) {
      printf("one table exists\n");
      tableFound = 1;
      temp = current->table;
      tables = NULL;
    }

    // if table is the first one
    if (tableFound == 0 && strcmp(current->table.name, yytext) == 0) {
      printf("table is the first one\n");
      tableFound = 1;
      temp = current->table;
      tables = current->next;
    }

    // if more than one table exists
    while (tableFound == 0 && current->next != NULL) {
      printf("current->next->table.name: %s\n", current->next->table.name);
      if (strcmp(current->next->table.name, yytext) == 0) {
        tableFound = 1;
        temp = current->next->table;
        current->next = current->next->next;
        break;
      }
      current = current->next;
    }

    // free the table
    if (tableFound) {
      free(temp.name);

      if (temp.constraint_name != NULL) {
        free(temp.constraint_name);
      }
      if (temp.primary_key != NULL) {
        free(temp.primary_key);
      }

      struct Column *current_column = temp.columns;
      while (current_column != NULL) {
        struct Column *tempCol = current_column;
        current_column = current_column->next;
        free(tempCol->name);
        free(tempCol->data_type);
        free(tempCol->constraint);
        free(tempCol);
      }
      printf("Table %s dropped\n", yytext);

      // print all tables names
      printf("Tables: ");
      current = tables;
      while (current != NULL) {
        printf("%s ", current->table.name);
        current = current->next;
      }
      printf(".\n");
    } else {
      printf("Invalid command\n");
    }
  }

  BEGIN(DROP_TABLE_NAME);
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 590 "sql_parser.l"
{
  BEGIN(INITIAL);
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 594 "sql_parser.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 595 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 596 "sql_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 598 "sql_parser.l"
{ printf("Invalid command\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 600 "sql_parser.l"
ECHO;
	YY_BREAK
#line 1857 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(TABLE_NAME):
case YY_STATE_EOF(COLUMN_NAME):
case YY_STATE_EOF(DATA_TYPE):
case YY_STATE_EOF(CONSTRAINT_NAME):
case YY_STATE_EOF(TABLE_PRIMARY_KEY):
case YY_STATE_EOF(DESCRIBE_TABLE_NAME):
case YY_STATE_EOF(DROP_TABLE_NAME):
case YY_STATE_EOF(PRIMARY_CONSTRAINT_NAME):
case YY_STATE_EOF(INSERT_TABLE_NAME):
case YY_STATE_EOF(INSERT_VALUES):
case YY_STATE_EOF(INSERT_COLUMNS):
case YY_STATE_EOF(INSERT):
case YY_STATE_EOF(ALTER_TABLE_NAME):
case YY_STATE_EOF(ALTER_TABLE):
case YY_STATE_EOF(ALTER_TABLE_ADD):
case YY_STATE_EOF(ALTER_TABLE_DROP):
case YY_STATE_EOF(ALTER_TABLE_ADD_TYPE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 263 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 263 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 262);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 600 "sql_parser.l"


int main(void) {
  yylex();
  return 0;
}

void yyerror(const char *s) {
  printf("Error: %s\n", s);
}
